//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplicationPractice.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ApplicationText() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplicationPractice.Properties.ApplicationText", typeof(ApplicationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancel_Button_Text {
            get {
                return ResourceManager.GetString("Cancel_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe de contener solamente letras..
        /// </summary>
        public static string Department_Name_Format_Error {
            get {
                return ResourceManager.GetString("Department_Name_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Empleado.
        /// </summary>
        public static string EditEmployee_Title_Text {
            get {
                return ResourceManager.GetString("EditEmployee_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La edad debe de ser entre 18 y 99 años..
        /// </summary>
        public static string Employee_Age_Range_Error {
            get {
                return ResourceManager.GetString("Employee_Age_Range_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad:.
        /// </summary>
        public static string Employee_AgeLabel_Text {
            get {
                return ResourceManager.GetString("Employee_AgeLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento:.
        /// </summary>
        public static string Employee_DepartmentLabel_Text {
            get {
                return ResourceManager.GetString("Employee_DepartmentLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto:.
        /// </summary>
        public static string Employee_JobLabel_Text {
            get {
                return ResourceManager.GetString("Employee_JobLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe de contener solamente Letras..
        /// </summary>
        public static string Employee_Name_Format_Error {
            get {
                return ResourceManager.GetString("Employee_Name_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede tener mas de 90 carácteres..
        /// </summary>
        public static string Employee_Name_Length_Error {
            get {
                return ResourceManager.GetString("Employee_Name_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string Employee_NameLabel_Text {
            get {
                return ResourceManager.GetString("Employee_NameLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El objeto proporcionado es incorrecto..
        /// </summary>
        public static string InvalidTypeErrror {
            get {
                return ResourceManager.GetString("InvalidTypeErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe de contener solamente letras..
        /// </summary>
        public static string Job_Name_Format_Error {
            get {
                return ResourceManager.GetString("Job_Name_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Ok_Button_Text {
            get {
                return ResourceManager.GetString("Ok_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo encontrar la propiedad {0}..
        /// </summary>
        public static string PropertyNameNotFound_Error {
            get {
                return ResourceManager.GetString("PropertyNameNotFound_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo es Requerido.
        /// </summary>
        public static string Required_Error {
            get {
                return ResourceManager.GetString("Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string Ribbon_AddUser_Text {
            get {
                return ResourceManager.GetString("Ribbon_AddUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Filtros.
        /// </summary>
        public static string Ribbon_ClearFilter_Text {
            get {
                return ResourceManager.GetString("Ribbon_ClearFilter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Ribbon_DeleteUser_Text {
            get {
                return ResourceManager.GetString("Ribbon_DeleteUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición.
        /// </summary>
        public static string Ribbon_EditionGroup_Text {
            get {
                return ResourceManager.GetString("Ribbon_EditionGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar....
        /// </summary>
        public static string Ribbon_EditUser_Text {
            get {
                return ResourceManager.GetString("Ribbon_EditUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Ribbon_Exit_Text {
            get {
                return ResourceManager.GetString("Ribbon_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda.
        /// </summary>
        public static string Ribbon_SearchGroup_Text {
            get {
                return ResourceManager.GetString("Ribbon_SearchGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        public static string Ribbon_SearchUser_Text {
            get {
                return ResourceManager.GetString("Ribbon_SearchUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        public static string Ribbon_ViewUserDetail_Text {
            get {
                return ResourceManager.GetString("Ribbon_ViewUserDetail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registo:.
        /// </summary>
        public static string StatusBar_CurrentIndex_Text {
            get {
                return ResourceManager.GetString("StatusBar_CurrentIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error Inesperado.
        /// </summary>
        public static string UnexpectedError_Caption {
            get {
                return ResourceManager.GetString("UnexpectedError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error: {0}.
        /// </summary>
        public static string UnexpectedError_Text {
            get {
                return ResourceManager.GetString("UnexpectedError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ninguna ventana para mostrar..
        /// </summary>
        public static string UnknownWindowError_Text {
            get {
                return ResourceManager.GetString("UnknownWindowError_Text", resourceCulture);
            }
        }
    }
}
